# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Loop < Formula
  desc "Discord bot powered by Claude that runs AI agents in Docker containers"
  homepage "https://github.com/radutopala/loop"
  version "2026.5.19"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/radutopala/loop/releases/download/v2026.5.19/loop_2026.5.19_darwin_amd64.tar.gz"
      sha256 "a1a78eea82cdf6ba0c39c0a3b28dd9c95b85e9c290a4dcb3d9f85fc52990a579"

      define_method(:install) do
        bin.install "loop"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/radutopala/loop/releases/download/v2026.5.19/loop_2026.5.19_darwin_arm64.tar.gz"
      sha256 "77e62d28c480570213acd868408c891342aad25b3d298fefa49279becebff587"

      define_method(:install) do
        bin.install "loop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/radutopala/loop/releases/download/v2026.5.19/loop_2026.5.19_linux_amd64.tar.gz"
      sha256 "903327b66b1d245b35a7c51fe75362bd4ad3b73523f1623035e6bfc06ba69d51"
      define_method(:install) do
        bin.install "loop"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/radutopala/loop/releases/download/v2026.5.19/loop_2026.5.19_linux_arm64.tar.gz"
      sha256 "d6ff1c7b5481c29369fad41976f0c75e7b91cac813eb5a24a9ffdbedddddf8e1"
      define_method(:install) do
        bin.install "loop"
      end
    end
  end

  test do
    system "#{bin}/loop", "--help"
  end
end
