# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tk < Formula
  desc "Minimal CLI ticket management system for AI agents"
  homepage "https://github.com/radutopala/ticket"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/radutopala/ticket/releases/download/v0.2.0/tk_0.2.0_darwin_amd64.tar.gz"
      sha256 "5a2d8746f12362254a4348ec5ef2a4b139b9618289e81cc244a033a20ca74691"

      def install
        bin.install "tk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/radutopala/ticket/releases/download/v0.2.0/tk_0.2.0_darwin_arm64.tar.gz"
      sha256 "543219b358b9a450b6751e4815716fcafb1e18ece45a2afe9d59663613223794"

      def install
        bin.install "tk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/radutopala/ticket/releases/download/v0.2.0/tk_0.2.0_linux_amd64.tar.gz"
      sha256 "8ce96a1d9a5147c1fb9b49198e33a18b8855c5abf2d51f62d5616da12fea23fd"
      def install
        bin.install "tk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/radutopala/ticket/releases/download/v0.2.0/tk_0.2.0_linux_arm64.tar.gz"
      sha256 "d70c8564c0b6bb5168e208b79b86f8f8d60ad9232469eddfc14b8f27fd6c9bab"
      def install
        bin.install "tk"
      end
    end
  end

  test do
    system "#{bin}/tk", "--help"
  end
end
