# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tk < Formula
  desc "Minimal CLI ticket management system for AI agents"
  homepage "https://github.com/radutopala/ticket"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/radutopala/ticket/releases/download/v0.2.1/tk_0.2.1_darwin_amd64.tar.gz"
      sha256 "9e9adad149cef73f7aced8758e3f40c80019dd3ade2e6f8145a0add74a391875"

      def install
        bin.install "tk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/radutopala/ticket/releases/download/v0.2.1/tk_0.2.1_darwin_arm64.tar.gz"
      sha256 "16748155cd17798f1411340d9c24d34a30fe5547113bf4f602e7418cfbee69cc"

      def install
        bin.install "tk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/radutopala/ticket/releases/download/v0.2.1/tk_0.2.1_linux_amd64.tar.gz"
      sha256 "8471fd57bac709422e622f0cd5844a3c31a7e92fe8456107c27aa67bf672ff0d"
      def install
        bin.install "tk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/radutopala/ticket/releases/download/v0.2.1/tk_0.2.1_linux_arm64.tar.gz"
      sha256 "0f50235dd2cbf81b18f7f798952291ee475a65e5e16c5b64b0910d3c1eb954b2"
      def install
        bin.install "tk"
      end
    end
  end

  test do
    system "#{bin}/tk", "--help"
  end
end
